### ISSUE TITLE
Remove cachier from dependencies 

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#159]
This originates from `snapshot` and `release` pipeline failures along the lines of:
```
02:39:12  running gaferencer with: `gaferencer gaf --ontfile true --contexts target/go_context.jsonld,target/obo_context.jsonld target/go-gaf.owl target/groups/paint/paint_sgd-src.gaf target/groups/paint/paint_sgd.gaferences.json`
02:40:08  Unzipping target/groups/goa/goa_human_complex-src.gaf.gz
02:40:08  running gaferencer with: `gaferencer gaf --ontfile true --contexts target/go_context.jsonld,target/obo_context.jsonld target/go-gaf.owl target/groups/goa/goa_human_complex-src.gaf target/groups/goa/goa_human_complex.gaferences.json`
02:40:08  Unzipping target/groups/paint/paint_tair-src.gaf.gz
02:40:08  running gaferencer with: `gaferencer gaf --ontfile true --contexts target/go_context.jsonld,target/obo_context.jsonld target/go-gaf.owl target/groups/paint/paint_tair-src.gaf target/groups/paint/paint_tair.gaferences.json`
02:40:54  Traceback (most recent call last):
02:40:54    File "/usr/local/bin/validate.py", line 28, in <module>
02:40:54      from ontobio.rdfgen import assoc_rdfgen
02:40:54    File "/usr/local/lib/python3.6/dist-packages/ontobio/rdfgen/assoc_rdfgen.py", line 27, in <module>
02:40:54      prefix_context = {key: value for context in curie_util.default_curie_maps + [curie_util.read_biocontext("go_context")] for key, value in context.items()}
02:40:54    File "/usr/local/lib/python3.6/dist-packages/cachier/core.py", line 189, in func_wrapper
02:40:54      return core.wait_on_entry_calc(key)
02:40:54    File "/usr/local/lib/python3.6/dist-packages/cachier/pickle_core.py", line 236, in wait_on_entry_calc
02:40:54      return self.wait_on_entry_calc(key)
02:40:54    File "/usr/local/lib/python3.6/dist-packages/cachier/pickle_core.py", line 236, in wait_on_entry_calc
02:40:54      return self.wait_on_entry_calc(key)
02:40:54    File "/usr/local/lib/python3.6/dist-packages/cachier/pickle_core.py", line 236, in wait_on_entry_calc
02:40:54      return self.wait_on_entry_calc(key)
02:40:54    [Previous line repeated 967 more times]
02:40:54    File "/usr/local/lib/python3.6/dist-packages/cachier/pickle_core.py", line 232, in wait_on_entry_calc
02:40:54      observer.start()
02:40:54    File "/usr/local/lib/python3.6/dist-packages/watchdog/observers/api.py", line 253, in start
02:40:54      emitter.start()
02:40:54    File "/usr/local/lib/python3.6/dist-packages/watchdog/utils/__init__.py", line 110, in start
02:40:54      self.on_thread_start()
02:40:54    File "/usr/local/lib/python3.6/dist-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
02:40:54      self._inotify = InotifyBuffer(path, self.watch.is_recursive)
02:40:54    File "/usr/local/lib/python3.6/dist-packages/watchdog/observers/inotify_buffer.py", line 33, in __init__
02:40:54      BaseThread.__init__(self)
02:40:54    File "/usr/local/lib/python3.6/dist-packages/watchdog/utils/__init__.py", line 69, in __init__
02:40:54      threading.Thread.__init__(self)
02:40:54    File "/usr/lib/python3.6/threading.py", line 793, in __init__
02:40:54      self._started = Event()
02:40:54    File "/usr/lib/python3.6/threading.py", line 499, in __init__
02:40:54      self._cond = Condition(Lock())
02:40:54    File "/usr/lib/python3.6/threading.py", line 226, in __init__
02:40:54      self._release_save = lock._release_save
02:40:54  RecursionError: maximum recursion depth exceeded while calling a Python object
02:40:54  Makefile:78: recipe for target 'target/groups/noctua/noctua.group' failed
02:40:54  make: *** [target/groups/noctua/noctua.group] Error 1
02:40:54  make: *** Waiting for unfinished jobs....
```

Talking with @deepakunni3 and @cmungall , it seems likely that we are being bitten by issues similar to what caused biolink/ontobio#358 , biolink/ontobio#321 , except now it's coming in through prefixcommons/curie_utils.

@deepakunni3 Is looking at removing it from prefixcommons and releasing a new ontobio to reflect that change.

**Comment by deepakunni3** [comment]
prefixcommons-py has been updated to `v0.1.9`.
ontobio is now at `v0.15.2`, which uses the latest version of prefixcommons-py.

This should fix the problem, or at least remove cachier from the equation.
