### ISSUE TITLE
Track down and evaluate "connection reset" issue

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#160]
Over the last month or so, we've had failures in the pipeline (and go-shapes) that seem to be associated with an upstream server connection reset while gathering ontologies. For example, some of the ones recently seen:

```
[2019-12-05T13:05:40.101Z]     return func(*args, **kwargs)
[2019-12-05T13:05:40.101Z]   File "/usr/lib/python3.6/socket.py", line 586, in readinto
[2019-12-05T13:05:40.101Z]     return self._sock.recv_into(b)
[2019-12-05T13:05:40.101Z] ConnectionResetError: [Errno 104] Connection reset by peer
[2019-12-05T13:05:41.012Z] Makefile:78: recipe for target 'target/groups/goa/goa.group' failed
[2019-12-05T13:05:41.012Z] make: *** [target/groups/goa/goa.group] Error 1
[2019-12-05T13:05:41.012Z] make: *** Waiting for unfinished jobs....
```

```
[2019-12-11T10:25:12.492Z] 2019-12-11 10:25:11,312 ERROR (CommandRunner:4815) could not parse:go-graphstore.owl
[2019-12-11T10:25:12.492Z] org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/go/extensions/go-lego.owl> Cause: Connection reset
[2019-12-11T10:25:12.492Z]     at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1870)
[2019-12-11T10:25:12.492Z]     at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.Ontology(OWLFunctionalSyntaxParser.java:231)
```

```
[2020-01-29T10:19:29.141Z] 2020-01-29 10:19:29,018 ERROR (CommandRunner:4815) could not parse:go-graphstore.owl
[2020-01-29T10:19:29.141Z] org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/go/extensions/go-lego.owl> Cause: Connection reset
```

```
2020-02-05 20:24:03,492 INFO  (CommandLineInterface:623) using catalog: ../../ontology/catalog-for-validation.xml
2020-02-05 20:24:03,510 INFO  (CommandLineInterface:630) neo mapped iri: file:/home/travis/build/geneontology/go-shapes/ontology/neo.owl
2020-02-05 20:24:03,627 INFO  (CommandLineInterface:632) neo axioms 0
2020-02-05 20:24:08,946 ERROR (Banner:160) Uncaught exception in thread
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/go/extensions/go-plus.owl> Cause: Connection reset
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1909)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.Ontology(OWLFunctionalSyntaxParser.java:231)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.parse(OWLFunctionalSyntaxParser.java:171)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParser.parse(OWLFunctionalSyntaxOWLParser.java:101)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:221)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1293)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1233)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1133)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1087)
	at org.geneontology.minerva.cli.CommandLineInterface.validateGoCams(CommandLineInterface.java:634)
	at org.geneontology.minerva.cli.CommandLineInterface.main(CommandLineInterface.java:281)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: Connection reset
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:231)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1293)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1233)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1133)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1864)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1902)
	... 10 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
	at org.apache.commons.io.input.BOMInputStream.read(BOMInputStream.java:348)
```

Farther back, the last rash of these was in July.

Tagging @vanaukenk and @dougli1sqrd

**Comment by kltm** [comment]
From experience, it often seems to related to 
http://purl.obolibrary.org/obo/go/extensions/go-lego.owl
http://purl.obolibrary.org/obo/go/extensions/go-plus.owl

**Comment by kltm** [comment]
So far, I've come up with nothing on purl.obolibrary.org that would indicate any kind of issue. There seem to be few recorded errors and the 302s from our likely sources seem fine.

**Comment by kltm** [comment]
There's not really much to go on with the CloudFront and S3 info that we have.
Yet the errors are there.

Given the lack of validation for any of my other theories concerning the PURL server, a new unsupported theory is that 1) the CF gets a miss as the S3 had been updated but 2) S3 does not respond or respond in time, causing a reset. Tests might be watching the S3 buckets, improving the timeout on origin (can that be done for S3 as it's not a custom origin?), or actually being able to test this while it's occurring.

**Comment by kltm** [comment]
Okay, I've tracked the final error above to this log line:
```
2020-02-05      20:24:08        YTO50-C1        2605324 35.202.145.110  GET     d29dhtshqop4im.cloudfront.net   /ontology/extensions/go-plus.owl        200     -       Java/1.8.0_141  -       -       Error   -FGI-3bzf8uDdWGXc-mSNXkkdsMmBbO8cb4p4CKc9LOYorlQ0OAhPQ==        current.geneontology.org        http    269     2.458   -       -       -       Hit     HTTP/1.1        -       -       38660   0.003   ClientCommError application/rdf+xml     233776756       -       -
```

**Comment by kltm** [comment]
Looking at other ClientCommError lines for 2020-02 so far, there is little pattern, and only the one for a travis IP address.

Okay, according to AWS then, it's fine and occasionally clients are calling in from networks that are having problems and they lose the connection. Given that, for us and the fact that this has happened occasionally on travis and at lbl, would be to build better clients that are more robust (or, I assume that AWS would argue that we should put our stuff in AWS). A disappointing result, but it's good to write robust things.

**Comment by kltm** [comment]
@vanaukenk The TL;DR is that this is something that's probably just going to happen sometimes and that moving forward software should just be better at dealing with things breaking on the wire: life in a intermittently connected world. I'll talk a little about this at a software call in the future.

**Comment by vanaukenk** [comment]
Thanks for looking into this @kltm
