### ISSUE TITLE
Checkout of go-ontology is too large / slow to allow "neo" (issue-35-neo-test) run

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#248]
Currently, checkout of go-ontology is too large / slow to allow for a "neo" (issue-35-neo-test) run to complete, getting hung up in the build go stage:

```
20:44:11  Fetching changes from the remote Git repository
20:44:11   > git config remote.origin.url https://github.com/geneontology/go-ontology.git # timeout=10
20:44:11  Fetching upstream changes from https://github.com/geneontology/go-ontology.git
20:44:11   > git --version # timeout=10
20:44:11   > git --version # 'git version 2.7.4'
20:44:11   > git fetch --tags --progress https://github.com/geneontology/go-ontology.git +refs/heads/*:refs/remotes/origin/* # timeout=10
20:54:11  ERROR: Timeout after 10 minutes
20:54:12  ERROR: Error fetching remote repo 'origin'
20:54:12  hudson.plugins.git.GitException: Failed to fetch from https://github.com/geneontology/go-ontology.git
20:54:12  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1004)
20:54:12  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1245)
20:54:12  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
20:54:12  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
20:54:12  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
20:54:12  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
20:54:12  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
20:54:12  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:54:12  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:54:12  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20:54:12  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20:54:12  	at java.lang.Thread.run(Thread.java:748)
20:54:12  Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/geneontology/go-ontology.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
20:54:12  stdout: 
20:54:12  stderr: remote: Enumerating objects: 51537, done.        
20:54:12  remote: Counting objects:   0% (1/1280)        
remote: Counting objects:   1% (13/1280)        
```
...
```

Resolving deltas:  82% (31998/38905)   
error: index-pack died of signal 15
20:54:12  fatal: index-pack failed
20:54:12  
20:54:12  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2681)
20:54:12  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2102)
20:54:12  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
20:54:12  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:624)
20:54:12  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1002)
20:54:12  	... 11 more
```

**Comment by kltm** [comment]
Tagging @vanaukenk -- the previous "neo" issue was fixed, but now we have a new problem.  Hopeful for end-of-week fix.

**Comment by kltm** [comment]
We have starting running into this issue again; after Dec 3, confirmed on Dec 10th.

**Comment by kltm** [comment]
Okay, trying to increase timeout instead of reducing checkout size/time seems to be effective (~11m).

**Comment by kltm** [comment]
This change seems to have had some kind of positive effect, but it doesn't seem to have affected all the timeouts. That said, a little hard to test due to other problems.

**Comment by kltm** [comment]
This seems to now be affecting `snapshot`(/`release`).

**Comment by kltm** [comment]
NEO also exhibiting this again.

**Comment by kltm** [comment]
All branches seem functional again, with the heavy lifting step now coming out as:
`git fetch --no-tags --progress --depth=1 https://github.com/geneontology/go-ontology.git +refs/heads/*:refs/remotes/origin/* # timeout=120`
So, `timeout` up, but for some reason my `refspec` modifications seems to have had no effect. I suppose that's moot if the timeout is now higher, but a little frustrating as I'm not sure what I'm doing wrong given the docs (https://www.jenkins.io/doc/pipeline/steps/workflow-scm-step/).

**Comment by cmungall** [comment]
So if the git repo is getting too large I assume we'll start seeing issues
with github actions too?

**Comment by kltm** [comment]
Honestly, I'm not entirely sure about that--it seems to be at least somewhat specific to the environment, how the repo is fetched, etc. I would expected that issues would have already showed up if there were going to be issues. That said, I also haven't really thought about that before now and I can't think of any reasons that it couldn't be a problem in the future.
