### ISSUE TITLE
Pipeline currently fails due to boto3 / botocore changing requirements

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#250]
The main publishing pipelines are currently failing due to issues like:
```
22:50:43  + python3 ./scripts/s3-uploader.py -v --credentials **** --directory /var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/mnt/snapshot/ --bucket go-data-product-snapshot --number 1586 --pipeline snapshot
22:50:43  Traceback (most recent call last):
22:50:43    File "./scripts/s3-uploader.py", line 28, in <module>
22:50:43      import boto3
22:50:43    File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/mypyenv/lib/python3.5/site-packages/boto3/__init__.py", line 16, in <module>
22:50:43      from boto3.session import Session
22:50:43    File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/mypyenv/lib/python3.5/site-packages/boto3/session.py", line 17, in <module>
22:50:43      import botocore.session
22:50:43    File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/mypyenv/lib/python3.5/site-packages/botocore/session.py", line 30, in <module>
22:50:43      import botocore.client
22:50:43    File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/mypyenv/lib/python3.5/site-packages/botocore/client.py", line 16, in <module>
22:50:43      from botocore.args import ClientArgsCreator
22:50:43    File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/mypyenv/lib/python3.5/site-packages/botocore/args.py", line 26, in <module>
22:50:43      from botocore.signers import RequestSigner
22:50:43    File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/mypyenv/lib/python3.5/site-packages/botocore/signers.py", line 19, in <module>
22:50:43      import botocore.auth
22:50:43    File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/mypyenv/lib/python3.5/site-packages/botocore/auth.py", line 121
22:50:43      pairs.append(f'{quoted_key}={quoted_value}')
22:50:43                                                ^
22:50:43  SyntaxError: invalid syntax
[Pipeline] }
```

It seems like this may be a library version / python version issue: locking in the libraries on that machine to an earlier version seems to get us through:

```
 python3 ./mypyenv/bin/pip3 install --force-reinstall boto3==1.18.52
 python3 ./mypyenv/bin/pip3 install --force-reinstall botocore==1.21.52
```

A little digging (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/migrationpy3.html#timeline) indicated that 3.5, what we use right now in that section, may have been deprecated some time ago:
`Going forward, all projects using Boto3 need to transition to Python 3.6 or later. Boto3 and Botocore ended support for Python 3.4 and 3.5 on Feb 21, 2021, and support for Python 2.7 ended July 15, 2021.`
I'm unsure why this was a sudden issue from around the 8th of this month, rather than six months ago, but here we are.

**Comment by kltm** [comment]
Long-term fix is fixed libraries in docker image or move up the python version.

**Comment by kltm** [comment]
This passed.

**Comment by kltm** [comment]
Now failing like:
```
00:06:46  + python3 ./scripts/s3-uploader.py -v --credentials **** --directory /var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/mnt/master/ --bucket go-data-product-experimental --number 658 --pipeline master
00:06:46  INFO:aggregate:Verbose: on
00:06:46  INFO:aggregate:Will use credentials: ****
00:06:46  INFO:aggregate:Will operate in: /var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/mnt/master
00:06:46  INFO:aggregate:Will put to bucket at top level: go-data-product-experimental
00:06:46  INFO:aggregate:Will use internal mimetype defaults
00:06:46  INFO:aggregate:Will use S3 bucket location default: us-east-1
00:06:47  Traceback (most recent call last):
00:06:47    File "./scripts/s3-uploader.py", line 227, in <module>
00:06:47      main()
00:06:47    File "./scripts/s3-uploader.py", line 149, in main
[...]
00:06:47    File "/var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/go-site/mypyenv/lib/python3.5/site-packages/boto3/s3/transfer.py", line 127, in <module>
00:06:47      from s3transfer.exceptions import RetriesExceededError as \
00:06:47    File "/var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/go-site/mypyenv/lib/python3.5/site-packages/s3transfer/__init__.py", line 592
00:06:47      range_param = f'bytes={start_range}-{end_range}'
00:06:47                                                     ^
00:06:47  SyntaxError: invalid syntax
```

**Comment by kltm** [comment]
Noting that this keeps having temporal overlaps with https://github.com/geneontology/pipeline/issues/262

**Comment by kltm** [comment]
False equivalence; actually: https://github.com/geneontology/pipeline/issues/271
