### ISSUE TITLE
Pipeline currently fails due to pystache changing requirements

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#262]
The main publishing pipelines are currently failing due to issues like:

```
18:07:13  + python3 ./mypyenv/bin/pip3 install pystache
18:07:13  Collecting pystache
18:07:14    Using cached https://files.pythonhosted.org/packages/3f/e7/8750ba6c6101d6aa5ceeb20c013adf2c6f3554a12c71d75654b468404bfa/pystache-0.6.0.tar.gz
18:07:14      Complete output from command python setup.py egg_info:
18:07:14      Traceback (most recent call last):
18:07:14        File "<string>", line 1, in <module>
18:07:14        File "/tmp/pip-build-641m5gq8/pystache/setup.py", line 183
18:07:14          command = f"pandoc -f markdown-smart --write=rst --output={rst_temp_path} {md_path}"
18:07:14                                                                                             ^
18:07:14      SyntaxError: invalid syntax
```

It seems like this may be a library version / python version issue.
I'm guessing related to pystache 0.6.0 coming out, 2021-12-08, after 0.5.4 in 2014 (!). This lines up with with failures at this point starting (at the latest) on the 8th.

**Comment by kltm** [comment]
Testing on `master`; `snapshot` will auto-trigger tonight in case it goes well.

**Comment by kltm** [comment]
`snapshot` now passing

**Comment by kltm** [comment]
This is now occurring in the "Archive" stage, where is previously was only happening in "Produce metadata". Will try applying the same fix. (Crazy that there was almost a two month lag there.)

**Comment by kltm** [comment]
Noting that this keeps having temporal overlaps with https://github.com/geneontology/pipeline/issues/262

**Comment by kltm** [comment]
Updates in for future proofing
