### ISSUE TITLE
Pipeline currently fails due to s3transfer changing requirements

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#271]
The main publishing pipelines are currently failing due to issues like:

```
00:06:46  + python3 ./scripts/s3-uploader.py -v --credentials **** --directory /var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/mnt/master/ --bucket go-data-product-experimental --number 658 --pipeline master
00:06:46  INFO:aggregate:Verbose: on
00:06:46  INFO:aggregate:Will use credentials: ****
00:06:46  INFO:aggregate:Will operate in: /var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/mnt/master
00:06:46  INFO:aggregate:Will put to bucket at top level: go-data-product-experimental
00:06:46  INFO:aggregate:Will use internal mimetype defaults
00:06:46  INFO:aggregate:Will use S3 bucket location default: us-east-1
00:06:47  Traceback (most recent call last):
00:06:47    File "./scripts/s3-uploader.py", line 227, in <module>
00:06:47      main()
00:06:47    File "./scripts/s3-uploader.py", line 149, in main
[...]
00:06:47    File "/var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/go-site/mypyenv/lib/python3.5/site-packages/boto3/s3/transfer.py", line 127, in <module>
00:06:47      from s3transfer.exceptions import RetriesExceededError as \
00:06:47    File "/var/lib/jenkins/workspace/eneontology_pipeline_master-652M4IO72SEALCAQPK6GJ6S47TOPEE2MMU5CG5KVER6NNUCGJH2A/go-site/mypyenv/lib/python3.5/site-packages/s3transfer/__init__.py", line 592
00:06:47      range_param = f'bytes={start_range}-{end_range}'
00:06:47                                                     ^
00:06:47  SyntaxError: invalid syntax
```

Similar to #250 and #262

**Comment by kltm** [comment]
A little digging seems to indicate that this break occurred going from `s3transfer` 0.5.0 -> 0.5.1 eight days ago. 
https://github.com/boto/s3transfer/commit/c039ef50cfc56d5310a7e9e2f36726a2ac89a5bc
Looking through that, it seems they low key discontinued support for 3.5--now just 3.6 up to 3.10.

**Comment by kltm** [comment]
I'll spin this out for future standardizing work, but just noting for now the scripts running outside of VMs are more-or-less happy with:
```
python3 --version
Python 3.5.2
```
```
python3 ./mypyenv/bin/pip3 list
awscli (1.22.52)
bagit (1.8.1)
bagit-profile (1.3.1)
bdbag (1.6.3)
boto3 (1.18.52)
botocore (1.21.52)
certifi (2021.10.8)
chardet (4.0.0)
charset-normalizer (2.0.11)
click (7.1.2)
colorama (0.4.3)
docutils (0.15.2)
filechunkio (1.8)
idna (2.10)
jmespath (0.10.0)
pip (8.1.1)
pkg-resources (0.0.0)
pyasn1 (0.4.8)
pycurl (7.44.1)
pypandoc (1.7.2)
pystache (0.5.4)
python-dateutil (2.8.2)
pytz (2021.3)
PyYAML (5.4.1)
requests (2.25.1)
requests-toolbelt (0.9.1)
rsa (4.7.2)
s3transfer (0.5.0)
setuptools (20.7.0)
setuptools-scm (5.0.2)
six (1.16.0)
tzlocal (2.1)
urllib3 (1.26.8)
yamldown (0.1.8)
```

**Comment by kltm** [comment]
Pass on `snapshot`
