### ISSUE TITLE
Pipeline currently fails due to antlr4 changing requirements

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#279]
The main publishing pipelines are currently failing due to issues like:
```
[2022-04-12T11:40:16.649Z]   File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
[2022-04-12T11:40:16.649Z]     self.checkVersion()
[2022-04-12T11:40:16.649Z]   File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
[2022-04-12T11:40:16.649Z]     raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
[2022-04-12T11:40:16.649Z] Exception: Could not deserialize ATN with version  (expected 4).
[2022-04-12T11:40:16.649Z] Traceback (most recent call last):
[2022-04-12T11:40:16.649Z]   File "/usr/local/bin/validate.py", line 32, in <module>
[2022-04-12T11:40:16.649Z]     from ontobio.rdfgen.gocamgen.gocam_builder import GoCamBuilder, AssocExtractor
[2022-04-12T11:40:16.649Z]   File "/usr/local/lib/python3.6/dist-packages/ontobio/rdfgen/gocamgen/gocam_builder.py", line 1, in <module>
[2022-04-12T11:40:16.649Z]     from ontobio.rdfgen.gocamgen.gocamgen import AssocGoCamModel
[...]
[2022-04-12T11:40:16.649Z] Exception: Could not deserialize ATN with version  (expected 4).
[2022-04-12T11:40:16.899Z] Makefile:84: recipe for target 'target/groups/noctua/noctua.group' failed
[2022-04-12T11:40:16.899Z] make: *** [target/groups/noctua/noctua.group] Error 1
[2022-04-12T11:40:16.899Z] make: *** Waiting for unfinished jobs....
[2022-04-12T11:40:17.810Z] Makefile:84: recipe for target 'target/groups/rnacentral/rnacentral.group' failed
[2022-04-12T11:40:17.810Z] make: *** [target/groups/rnacentral/rnacentral.group] Error 1
[2022-04-12T11:40:18.061Z] Makefile:84: recipe for target 'target/groups/xenbase/xenbase.group' failed
[2022-04-12T11:40:18.061Z] make: *** [target/groups/xenbase/xenbase.group] Error 1
[2022-04-12T11:43:54.307Z] Unzipping target/groups/genedb/genedb_tbrucei-src.gaf.gz
```

Research from @dustine32 suggests this is due to `antlr4` updating from `4.9.3` to `4.10`

**Comment by kltm** [comment]
Thanks @dustine32 
Testing on `master`

**Comment by kltm** [comment]
@dustine32 Cleared and is naturally propagated--thank you!
