### ISSUE TITLE
Jenkins new snapshot pipeline failing early on "General error during class generation: Method too large..."

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#374]
```
Obtained Jenkinsfile from 9fe164d9aa2ee9cadece2928dbe6a4a30f3c98dc
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during class generation: Method too large: WorkflowScript.___cps___8459 ()Lcom/cloudbees/groovy/cps/impl/CpsFunction;

groovyjarjarasm.asm.MethodTooLargeException: Method too large: WorkflowScript.___cps___8459 ()Lcom/cloudbees/groovy/cps/impl/CpsFunction;
	at groovyjarjarasm.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
	at groovyjarjarasm.asm.ClassWriter.toByteArray(ClassWriter.java:447)
```

I'm guessing this is basically https://github.com/geneontology/pipeline/issues/183

**Comment by kltm** [comment]
Okay, ticking over again.
