### ISSUE TITLE
Error in ontobio prevents parsing some files

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#385]
Pipeline is currently failing due to `ontobio` parse issue
https://github.com/biolink/ontobio/issues/689

**Comment by kltm** [comment]
Temporarily reverting ontobio version to get `snapshot`s through

**Comment by kltm** [comment]
To clarify here: the end goal is to be outputting GPAD 2.0 in the pipeline, for the "next" release. To that end, we want to get the latest version of ontobio working in the pipeline. This issue is clearly expressed here: https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/2166/console

with possible example trace here:

```
02:10:54  Zipping /opt/go-site/pipeline/target/groups/rgd/rgd.gaf
02:10:54  Pre-isoform fix gaf file.../opt/go-site/pipeline/target/groups/rgd/rgd.gaf
02:10:54  Executing the isoform fixing step in validate.produce...
02:10:54  temp_output_gaf_path: /opt/go-site/pipeline/target/groups/rgd/rgd_temp.gaf
02:10:54  2024-09-07 09:10:53 [INFO] [PID:5971 TID:140341894443008] [assocparser.py:888 in `_ensure_file`]  Ensure file: None
02:10:54  Traceback (most recent call last):
02:10:54    File "/usr/local/bin/validate.py", line 1008, in <module>
02:10:54      cli(obj={})
02:10:54    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
02:10:54      return self.main(*args, **kwargs)
02:10:54    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
02:10:54      rv = self.invoke(ctx)
02:10:54    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
02:10:54      return _process_result(sub_ctx.command.invoke(sub_ctx))
02:10:54    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
02:10:54      return ctx.invoke(self.callback, **ctx.params)
02:10:54    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
02:10:54      return __callback(*args, **kwargs)
02:10:54    File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
02:10:54      return f(get_current_context(), *args, **kwargs)
02:10:54    File "/usr/local/bin/validate.py", line 768, in produce
02:10:54      isoform_fixed_gaf = fix_pro_isoforms_in_gaf(end_gaf, matching_gpi_path, ontology_graph, temp_output_gaf_path)
02:10:54    File "/usr/local/bin/validate.py", line 801, in fix_pro_isoforms_in_gaf
02:10:54      gpis = gpiparser.parse(gpi_file, None)
02:10:54    File "/usr/local/lib/python3.10/dist-packages/ontobio/io/entityparser.py", line 40, in parse
02:10:54      for line in file:
02:10:54  TypeError: 'NoneType' object is not iterable
02:10:54  make: *** [Makefile:86: target/groups/rgd/rgd.group] Error 1
```

The theory is that the right files are not in the expected place for the "new" parser to work.

**Comment by kltm** [comment]
After some iteration, it looks like we're operating normally again.
Thank you @sierra-moxon, @balhoff, and @dustine32 !
